Feat/integration tests on actions
commerceblock/mercurylayer pull request #64
Opened 2024-06-21 09:11 UTC by DhananjayPurohit

2024-06-25 16:14 UTC, ssantos21 requested changes
Sounds good to me, but there are some issues to be addressed.

2024-06-25 16:14 UTC, ssantos21 commented on clients/libs/nodejs/transaction.js
> +        console.log('Response:', response.data);
This can be removed.

```suggestion
```

2024-06-25 16:14 UTC, ssantos21 commented on clients/libs/nodejs/transaction.js
> +        console.log('Response:', response.data);
This can be removed.

```suggestion
```

2024-06-25 16:14 UTC, ssantos21 commented on clients/libs/nodejs/utils.js
> +    console.log("fee_rate_btc_per_kb:", fee_rate_btc_per_kb);
This can be removed.

```suggestion
```

2024-06-25 16:14 UTC, ssantos21 commented on clients/libs/nodejs/utils.js
> +    console.log("fee_rate_sats_per_byte: " + fee_rate_sats_per_byte);
This can be removed.

```suggestion
```

2024-06-25 16:14 UTC, ssantos21 commented on server/src/endpoints/deposit.rs
> +                "payload": statechain_id.clone(),
Why is this ` payload` field being added ?

```suggestion
```

2024-06-26 08:14 UTC, DhananjayPurohit commented on entrypoint.sh
> +#!/bin/bash
I wrote that before to create db manually for electrs but not needed anymore. Removing that.

2024-06-26 08:19 UTC, DhananjayPurohit commented on server/src/endpoints/deposit.rs
> +                "payload": statechain_id.clone(),
Added that time for debugging, no more needed.

2024-06-26 08:26 UTC, DhananjayPurohit commented on clients/libs/nodejs/index.js
> +const path = require('path');
Not needed anymore, Thanks.

2024-06-26 08:26 UTC, DhananjayPurohit commented on clients/libs/nodejs/index.js
> +    getElectrumClient
Not needed anymore, Thanks.

2024-06-28 16:38 UTC, merged